### ISSUE TITLE
error=>#<NoMethodError: undefined method `start_with?' for nil:NilClass>

### ISSUE THREAD

**Issue by amodakvnera** [logstash-plugins/logstash-filter-elasticsearch#25]
Hello,
While using this filter to search for previous events with logstash version 2.2.3 and elasticsearch version 2.3.0. I am getting below error -
  _error NoMethodError: undefined method `start_with?' for nil:NilClass level warn _

I am using it like below -
  elasticsearch {
    hosts => ["localhost:9205"]
  }

This same plugin works with logstash version 2.2.2.

Any fix / workaround for this?

Thanks.

**Comment by amodakvnera** [comment]
I also tried using 
elasticsearch {
hosts => ["http://localhost:9205"]
}
but still does not work.

**Comment by NXP-TWA** [comment]
Hi amodakvnera,

I am running into the same issue, did you manage to fix it ?


Best, T.

**Comment by juliuszc** [comment]
I had the same issue, and looking into the eslogs helped. It turned out that I was searching for a field that wasn't in all of the indices and when it searched in that index, it failed.
